name: Azure Web App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    # Step 2: Login to Azure using the service principal
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Create the Resource Group (if it doesn't exist)
    - name: 'Create Resource Group'
      run: |
        az group create --name myResourceGroup --location eastus

    # Step 4: Check if the Web App exists and set an output variable
    - name: 'Check if Web App exists'
      id: check_app
      run: |
        if az webapp show --resource-group myResourceGroup --name myFirstAzureApp; then
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "exists=false" >> $GITHUB_ENV
        fi

    # Step 5: Create the Web App if it doesn't exist
    - name: 'Create Azure Web App'
      if: env.exists == 'false'
      run: |
        az webapp create --resource-group myResourceGroup --plan myAppServicePlan --name myFirstAzureApp --runtime "node|14-lts"

    # Step 6: Deploy static files directly to the Azure Web App
    - name: 'Deploy to Azure Web App'
      run: |
        az webapp deploy --resource-group myResourceGroup --name myFirstAzureApp --src-path .
