name: Azure Web App Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # Step 2: Login to Azure using the service principal
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Create the Resource Group (if it doesn't exist)
    - name: 'Create Resource Group'
      run: |
        az group create --name myResourceGroup --location eastus

    # Step 4: Create Deployment Package (zip the project)
    - name: 'Create Deployment Package'
      run: zip -r my-app.zip .

    # Step 5: Deploy to Azure Web App using the zip package
    - name: 'Deploy to Azure Web App'
      run: |
        az webapp deploy --resource-group myResourceGroup --name myUniqueAzureApp --src-path ./my-app.zip --type static
