name: Azure Infrastructure Setup

on:
  push:
    branches:
      - main

jobs:
  setup-infrastructure:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository code
    - name: 'Checkout GitHub repository'
      uses: actions/checkout@v2

    # Step 2: Login to Azure using the service principal
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Create the Resource Group
    - name: 'Create Resource Group'
      run: |
        az group create --name myResourceGroup --location eastus

    # Step 4: Create a Virtual Network (VNet)
    - name: 'Create Virtual Network'
      run: |
        az network vnet create \
          --resource-group myResourceGroup \
          --name myVNet \
          --address-prefix 10.0.0.0/16 \
          --subnet-name mySubnet \
          --subnet-prefix 10.0.1.0/24
